# Supabase local development configuration

[api]
enabled = true
port = 54321
max_rows = 1000

[db]
port = 54322
major_version = 15

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[storage]
enabled = true

[auth]
enable_signup = true