#!/usr/bin/env node
/**
 * Explicit Data API grants catch-up (Supabase 2026-10-30 change: new objects in
 * `public` are no longer auto-granted to anon, authenticated, service_role).
 * Pattern follows sailorskills marketplace #159 and needs-are-normal #10, plus
 * sequences (serial/identity inserts need USAGE on the sequence).
 *
 *   node scripts/grants-catchup/build.mjs fetch    snapshot live grants into manifest.json (read-only endpoint)
 *   node scripts/grants-catchup/build.mjs render   write the migration + verify-noop.sql
 *   node scripts/grants-catchup/build.mjs check    fail if either file differs from a fresh render
 *   node scripts/grants-catchup/build.mjs verify   run verify-noop.sql against the live project (expect 0 rows)
 *   node scripts/grants-catchup/build.mjs query    print the read-only catalog query used for manifest.json
 *
 * fetch and verify use the Management API read-only SQL endpoint
 * (POST /v1/projects/{ref}/database/query/read-only). Token: SUPABASE_ACCESS_TOKEN
 * or ~/.supabase/access-token. Neither command can write to the database.
 *
 * scope.json holds the project ref, the migration version, relations that no
 * migration in this repo owns, and do-not-perpetuate exclusions. The migration
 * is GRANT-only, existence-guarded, and a strict subset of prod, so applying it
 * to prod is a no-op; verify-noop.sql proves that (expect zero rows).
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { homedir } from 'node:os';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = join(HERE, '..', '..');
const scope = JSON.parse(readFileSync(join(HERE, 'scope.json'), 'utf8'));
const MIGRATION_NAME = `${scope.migrationVersion}_explicit_data_api_grants_catchup.sql`;
export const MIGRATION = join(ROOT, 'supabase', 'migrations', MIGRATION_NAME);
const MANIFEST = join(HERE, 'manifest.json');
const VERIFY = join(HERE, 'verify-noop.sql');
const q = (s) => `'${String(s).replace(/'/g, "''")}'`;
const outOfScope = new Set(scope.outOfScopeRelations.relations);
const loadManifest = () => JSON.parse(readFileSync(MANIFEST, 'utf8'));

function excluded(rel, role, priv) {
  return scope.exclusions.some((e) => e.role === role && e.privileges.includes(priv) && e.relations.includes(rel));
}

export function expected(manifest = loadManifest()) {
  const rel = manifest.rel_grants.filter(([r, role, p]) => !outOfScope.has(r) && !excluded(r, role, p));
  const seq = manifest.seq_grants.filter(([s]) => !outOfScope.has(s));
  const col = manifest.col_grants.filter(([r]) => !outOfScope.has(r));
  const fn = manifest.fn_grants;
  return { rel, seq, col, fn };
}

function group(rows, keyFn) {
  const m = new Map();
  for (const row of rows) {
    const k = keyFn(row);
    if (!m.has(k)) m.set(k, []);
    m.get(k).push(row);
  }
  return [...m.entries()].sort(([a], [b]) => a.localeCompare(b));
}

function renderMigration() {
  const manifest = loadManifest();
  const { rel, seq, col, fn } = expected(manifest);
  const lines = [];
  lines.push(`-- ${MIGRATION_NAME}`);
  lines.push('--');
  lines.push('-- Explicit Data API grants catch-up (Supabase 2026-10-30 default-privileges change).');
  lines.push('-- GENERATED by scripts/grants-catchup/build.mjs from manifest.json (prod snapshot');
  lines.push(`-- ${manifest.snapshot}, project ${manifest.project}) and scope.json. Do not hand-edit; run render.`);
  lines.push('--');
  lines.push('-- WHY: from 2026-10-30 Supabase stops auto-granting table, sequence, and function');
  lines.push('--   privileges in public to anon/authenticated/service_role. Prod keeps what it has,');
  lines.push('--   but a REPLAY (local db reset, preview branch, new project) of this repo would');
  lines.push('--   create tables nobody can reach, because the earlier migrations never granted.');
  lines.push('--   This file re-states the needed subset of prod grants so a replay matches prod.');
  lines.push('--');
  lines.push('-- WHAT: GRANT-only, existence-guarded, a strict subset of prod. Applying it to prod');
  lines.push('--   is a no-op; scripts/grants-catchup/verify-noop.sql proves it (expect zero rows).');
  lines.push('--   PUBLIC-executable functions are omitted (the built-in PUBLIC EXECUTE is unaffected).');
  if (scope.outOfScopeRelations.relations.length) {
    lines.push('--');
    lines.push(`-- OUT OF SCOPE: ${scope.outOfScopeRelations.relations.join(', ')}.`);
    lines.push(`--   ${scope.outOfScopeRelations.reason}`);
  }
  if (scope.exclusions.length) {
    lines.push('--');
    lines.push('-- DO-NOT-PERPETUATE EXCLUSIONS (present in prod, deliberately not granted here):');
    for (const e of scope.exclusions) {
      lines.push(`--   * ${e.privileges.join('/')} for ${e.role} on ${e.relations.join(', ')}.`);
      lines.push(`--     ${e.reason}`);
    }
  }
  lines.push('');
  lines.push('do $grants$');
  lines.push('begin');
  for (const [r, rows] of group(rel, ([r]) => r)) {
    lines.push(`  if pg_catalog.to_regclass(${q('public.' + r)}) is not null then`);
    for (const [role, privs] of group(rows, ([, role]) => role)) {
      const list = privs.map(([, , p]) => p).sort().join(', ');
      lines.push(`    grant ${list} on table public.${r} to ${role};`);
    }
    lines.push('  end if;');
  }
  for (const [s, rows] of group(seq, ([s]) => s)) {
    lines.push(`  if pg_catalog.to_regclass(${q('public.' + s)}) is not null then`);
    for (const [role, privs] of group(rows, ([, role]) => role)) {
      const list = privs.map(([, , p]) => p).sort().join(', ');
      lines.push(`    grant ${list} on sequence public.${s} to ${role};`);
    }
    lines.push('  end if;');
  }
  for (const [key, rows] of group(col, ([r, c]) => `${r}.${c}`)) {
    const [r, c] = key.split('.');
    lines.push(`  if exists (select 1 from pg_catalog.pg_attribute where attrelid = pg_catalog.to_regclass(${q('public.' + r)}) and attname = ${q(c)} and not attisdropped) then`);
    for (const [, , role, p] of rows) lines.push(`    grant ${p} (${c}) on table public.${r} to ${role};`);
    lines.push('  end if;');
  }
  for (const [sig, rows] of group(fn, ([n, a]) => `${n}(${a})`)) {
    lines.push(`  if pg_catalog.to_regprocedure(${q('public.' + sig)}) is not null then`);
    lines.push(`    grant execute on function public.${sig} to ${rows.map(([, , role]) => role).sort().join(', ')};`);
    lines.push('  end if;');
  }
  lines.push('end');
  lines.push('$grants$;');
  lines.push('');
  return lines.join('\n');
}

export function catalogQuery() {
  return `with api_roles as (select oid, rolname from pg_roles where rolname in ('anon','authenticated','service_role')),
rel as (select c.oid, c.relname, c.relkind, c.relacl from pg_class c where c.relnamespace = 'public'::regnamespace and c.relkind in ('r','p','v','m','f','S')
        and not exists (select 1 from pg_depend d where d.objid = c.oid and d.deptype = 'e')),
fn as (select p.oid, p.proname, oidvectortypes(p.proargtypes) args, p.proacl,
              exists (select 1 from aclexplode(coalesce(p.proacl, acldefault('f', p.proowner))) x where x.grantee = 0 and x.privilege_type = 'EXECUTE') public_exec
       from pg_proc p where p.pronamespace = 'public'::regnamespace and p.prokind in ('f','p')
       and not exists (select 1 from pg_depend d where d.objid = p.oid and d.deptype = 'e')),
actual as (
  select 'rel'::text t, r.relname::text a, ''::text b, ro.rolname::text role, x.privilege_type::text priv, pg_get_userbyid(x.grantor)::text grantor
  from rel r cross join lateral aclexplode(r.relacl) x join api_roles ro on ro.oid = x.grantee
  where r.relkind <> 'S' and x.privilege_type in ('SELECT','INSERT','UPDATE','DELETE')
  union all
  select 'seq', r.relname, '', ro.rolname, x.privilege_type, pg_get_userbyid(x.grantor)
  from rel r cross join lateral aclexplode(r.relacl) x join api_roles ro on ro.oid = x.grantee
  where r.relkind = 'S' and x.privilege_type in ('USAGE','SELECT','UPDATE')
  union all
  select 'col', r.relname, a.attname, ro.rolname, x.privilege_type, pg_get_userbyid(x.grantor)
  from rel r join pg_attribute a on a.attrelid = r.oid and a.attnum > 0 and not a.attisdropped and a.attacl is not null
  cross join lateral aclexplode(a.attacl) x join api_roles ro on ro.oid = x.grantee
  where x.privilege_type in ('SELECT','INSERT','UPDATE')
  union all
  select 'fn', f.proname, f.args, ro.rolname, 'EXECUTE', pg_get_userbyid(x.grantor)
  from fn f cross join lateral aclexplode(f.proacl) x join api_roles ro on ro.oid = x.grantee
  where not f.public_exec and x.privilege_type = 'EXECUTE'
)`;
}

function renderVerify() {
  const { rel, seq, col, fn } = expected();
  const vals = [
    ...rel.map(([r, role, p]) => `('rel', ${q(r)}, '', ${q(role)}, ${q(p)})`),
    ...seq.map(([s, role, p]) => `('seq', ${q(s)}, '', ${q(role)}, ${q(p)})`),
    ...col.map(([r, c, role, p]) => `('col', ${q(r)}, ${q(c)}, ${q(role)}, ${q(p)})`),
    ...fn.map(([n, a, role]) => `('fn', ${q(n)}, ${q(a)}, ${q(role)}, 'EXECUTE')`),
  ];
  const excl = scope.exclusions.flatMap((e) => e.relations.flatMap((r) => e.privileges.map((p) => `('rel', ${q(r)}, '', ${q(e.role)}, ${q(p)})`)));
  // Typed empty-set fallbacks keep the SQL valid when a list is empty.
  const exclSql = excl.length ? `values\n  ${excl.join(',\n  ')}` : `select ''::text, ''::text, ''::text, ''::text, ''::text where false`;
  const oosSql = outOfScope.size ? `values ${[...outOfScope].map((r) => `(${q(r)})`).join(', ')}` : `select ''::text where false`;
  return `-- verify-noop.sql (GENERATED by scripts/grants-catchup/build.mjs render; do not hand-edit)
--
-- READ-ONLY proof that ${MIGRATION_NAME} is a
-- no-op against prod. EXPECT ZERO ROWS. Any row is a reason NOT to apply.
--   missing_in_prod:     the file grants something prod does not already hold
--                        with grantor postgres (applying would change prod).
--   in_prod_not_in_file: prod holds an in-scope privilege the file does not
--                        re-state (a replay would be tighter than prod).
--                        Exclusions and out-of-scope relations are skipped.
-- Run with \`node scripts/grants-catchup/build.mjs verify\`, Supabase MCP execute_sql,
-- or the SQL editor; it only SELECTs.
${catalogQuery()},
expected(t, a, b, role, priv) as (values
  ${vals.join(',\n  ')}
),
excluded(t, a, b, role, priv) as (${exclSql}),
out_of_scope(a) as (${oosSql})
select 'missing_in_prod' as problem, e.* from expected e
where not exists (select 1 from actual x where x.t = e.t and x.a = e.a and x.b = e.b and x.role = e.role and x.priv = e.priv and x.grantor = 'postgres')
union all
select 'in_prod_not_in_file', x.t, x.a, x.b, x.role, x.priv from actual x
where not exists (select 1 from expected e where e.t = x.t and e.a = x.a and e.b = x.b and e.role = x.role and e.priv = x.priv)
  and not exists (select 1 from excluded e where e.t = x.t and e.a = x.a and e.role = x.role and e.priv = x.priv)
  and x.a not in (select a from out_of_scope)
order by 1, 2, 3, 4, 5, 6;
`;
}

async function readOnlyQuery(sql) {
  const token = (process.env.SUPABASE_ACCESS_TOKEN || readFileSync(join(homedir(), '.supabase', 'access-token'), 'utf8')).trim();
  const res = await fetch(`https://api.supabase.com/v1/projects/${scope.project}/database/query/read-only`, {
    method: 'POST',
    headers: { Authorization: `Bearer ${token}`, 'Content-Type': 'application/json' },
    body: JSON.stringify({ query: sql }),
  });
  const text = await res.text();
  if (!res.ok) throw new Error(`read-only query failed: ${res.status} ${text}`);
  return JSON.parse(text);
}

const cmd = process.argv[2];
if (cmd === 'fetch') {
  const rows = await readOnlyQuery(catalogQuery() + '\nselect t, a, b, role, priv, grantor from actual order by 1, 2, 3, 4, 5;');
  const nonPostgres = rows.filter((r) => r.grantor !== 'postgres');
  if (nonPostgres.length) console.warn('note: grants with a grantor other than postgres (verify will flag them):', nonPostgres);
  const pick = (t, f) => rows.filter((r) => r.t === t).map(f);
  const manifest = {
    project: scope.project,
    snapshot: new Date().toISOString().slice(0, 10),
    note: 'Read-only snapshot of Data API grants in schema public (roles anon, authenticated, service_role), taken with build.mjs fetch. Privileges limited to those the Supabase 2026-10-30 change stops auto-granting. Extension-owned objects excluded.',
    rel_grants: pick('rel', (r) => [r.a, r.role, r.priv]),
    seq_grants: pick('seq', (r) => [r.a, r.role, r.priv]),
    col_grants: pick('col', (r) => [r.a, r.b, r.role, r.priv]),
    fn_grants: pick('fn', (r) => [r.a, r.b, r.role]),
  };
  writeFileSync(MANIFEST, JSON.stringify(manifest, null, 2) + '\n');
  console.log(`manifest: ${manifest.rel_grants.length} rel, ${manifest.seq_grants.length} seq, ${manifest.col_grants.length} col, ${manifest.fn_grants.length} fn grants`);
} else if (cmd === 'render') {
  writeFileSync(MIGRATION, renderMigration());
  writeFileSync(VERIFY, renderVerify());
  console.log('rendered', MIGRATION, VERIFY);
} else if (cmd === 'check') {
  const bad = [[MIGRATION, renderMigration()], [VERIFY, renderVerify()]].filter(([p, s]) => readFileSync(p, 'utf8') !== s);
  if (bad.length) { console.error('stale generated files:', bad.map(([p]) => p).join(', ')); process.exit(1); }
  console.log('generated files are current');
} else if (cmd === 'verify') {
  const rows = await readOnlyQuery(readFileSync(VERIFY, 'utf8'));
  for (const r of rows) console.log(JSON.stringify(r));
  console.log(`${rows.length} row(s) against ${scope.project}${rows.length ? ' -- NOT a no-op, do not apply' : ' -- no-op confirmed'}`);
  process.exit(rows.length ? 1 : 0);
} else if (cmd === 'query') {
  console.log(catalogQuery() + `\nselect * from actual order by 1, 2, 3, 4, 5;`);
} else {
  console.error('usage: build.mjs fetch|render|check|verify|query');
  process.exit(2);
}
