-- verify-noop.sql (GENERATED by scripts/grants-catchup/build.mjs render; do not hand-edit)
--
-- READ-ONLY proof that 20261005000000_explicit_data_api_grants_catchup.sql is a
-- no-op against prod. EXPECT ZERO ROWS. Any row is a reason NOT to apply.
--   missing_in_prod:     the file grants something prod does not already hold
--                        with grantor postgres (applying would change prod).
--   in_prod_not_in_file: prod holds an in-scope privilege the file does not
--                        re-state (a replay would be tighter than prod).
--                        Exclusions and out-of-scope relations are skipped.
-- Run with `node scripts/grants-catchup/build.mjs verify`, Supabase MCP execute_sql,
-- or the SQL editor; it only SELECTs.
with api_roles as (select oid, rolname from pg_roles where rolname in ('anon','authenticated','service_role')),
rel as (select c.oid, c.relname, c.relkind, c.relacl from pg_class c where c.relnamespace = 'public'::regnamespace and c.relkind in ('r','p','v','m','f','S')
        and not exists (select 1 from pg_depend d where d.objid = c.oid and d.deptype = 'e')),
fn as (select p.oid, p.proname, oidvectortypes(p.proargtypes) args, p.proacl,
              exists (select 1 from aclexplode(coalesce(p.proacl, acldefault('f', p.proowner))) x where x.grantee = 0 and x.privilege_type = 'EXECUTE') public_exec
       from pg_proc p where p.pronamespace = 'public'::regnamespace and p.prokind in ('f','p')
       and not exists (select 1 from pg_depend d where d.objid = p.oid and d.deptype = 'e')),
actual as (
  select 'rel'::text t, r.relname::text a, ''::text b, ro.rolname::text role, x.privilege_type::text priv, pg_get_userbyid(x.grantor)::text grantor
  from rel r cross join lateral aclexplode(r.relacl) x join api_roles ro on ro.oid = x.grantee
  where r.relkind <> 'S' and x.privilege_type in ('SELECT','INSERT','UPDATE','DELETE')
  union all
  select 'seq', r.relname, '', ro.rolname, x.privilege_type, pg_get_userbyid(x.grantor)
  from rel r cross join lateral aclexplode(r.relacl) x join api_roles ro on ro.oid = x.grantee
  where r.relkind = 'S' and x.privilege_type in ('USAGE','SELECT','UPDATE')
  union all
  select 'col', r.relname, a.attname, ro.rolname, x.privilege_type, pg_get_userbyid(x.grantor)
  from rel r join pg_attribute a on a.attrelid = r.oid and a.attnum > 0 and not a.attisdropped and a.attacl is not null
  cross join lateral aclexplode(a.attacl) x join api_roles ro on ro.oid = x.grantee
  where x.privilege_type in ('SELECT','INSERT','UPDATE')
  union all
  select 'fn', f.proname, f.args, ro.rolname, 'EXECUTE', pg_get_userbyid(x.grantor)
  from fn f cross join lateral aclexplode(f.proacl) x join api_roles ro on ro.oid = x.grantee
  where not f.public_exec and x.privilege_type = 'EXECUTE'
),
expected(t, a, b, role, priv) as (values
  ('rel', 'images', '', 'anon', 'DELETE'),
  ('rel', 'images', '', 'anon', 'INSERT'),
  ('rel', 'images', '', 'anon', 'SELECT'),
  ('rel', 'images', '', 'anon', 'UPDATE'),
  ('rel', 'images', '', 'authenticated', 'DELETE'),
  ('rel', 'images', '', 'authenticated', 'INSERT'),
  ('rel', 'images', '', 'authenticated', 'SELECT'),
  ('rel', 'images', '', 'authenticated', 'UPDATE'),
  ('rel', 'images', '', 'service_role', 'DELETE'),
  ('rel', 'images', '', 'service_role', 'INSERT'),
  ('rel', 'images', '', 'service_role', 'SELECT'),
  ('rel', 'images', '', 'service_role', 'UPDATE'),
  ('rel', 'leaderboard_entries', '', 'anon', 'DELETE'),
  ('rel', 'leaderboard_entries', '', 'anon', 'INSERT'),
  ('rel', 'leaderboard_entries', '', 'anon', 'SELECT'),
  ('rel', 'leaderboard_entries', '', 'anon', 'UPDATE'),
  ('rel', 'leaderboard_entries', '', 'authenticated', 'DELETE'),
  ('rel', 'leaderboard_entries', '', 'authenticated', 'INSERT'),
  ('rel', 'leaderboard_entries', '', 'authenticated', 'SELECT'),
  ('rel', 'leaderboard_entries', '', 'authenticated', 'UPDATE'),
  ('rel', 'leaderboard_entries', '', 'service_role', 'DELETE'),
  ('rel', 'leaderboard_entries', '', 'service_role', 'INSERT'),
  ('rel', 'leaderboard_entries', '', 'service_role', 'SELECT'),
  ('rel', 'leaderboard_entries', '', 'service_role', 'UPDATE'),
  ('rel', 'leaderboard_weeks', '', 'anon', 'DELETE'),
  ('rel', 'leaderboard_weeks', '', 'anon', 'INSERT'),
  ('rel', 'leaderboard_weeks', '', 'anon', 'SELECT'),
  ('rel', 'leaderboard_weeks', '', 'anon', 'UPDATE'),
  ('rel', 'leaderboard_weeks', '', 'authenticated', 'DELETE'),
  ('rel', 'leaderboard_weeks', '', 'authenticated', 'INSERT'),
  ('rel', 'leaderboard_weeks', '', 'authenticated', 'SELECT'),
  ('rel', 'leaderboard_weeks', '', 'authenticated', 'UPDATE'),
  ('rel', 'leaderboard_weeks', '', 'service_role', 'DELETE'),
  ('rel', 'leaderboard_weeks', '', 'service_role', 'INSERT'),
  ('rel', 'leaderboard_weeks', '', 'service_role', 'SELECT'),
  ('rel', 'leaderboard_weeks', '', 'service_role', 'UPDATE'),
  ('rel', 'profiles', '', 'anon', 'DELETE'),
  ('rel', 'profiles', '', 'anon', 'INSERT'),
  ('rel', 'profiles', '', 'anon', 'SELECT'),
  ('rel', 'profiles', '', 'anon', 'UPDATE'),
  ('rel', 'profiles', '', 'authenticated', 'DELETE'),
  ('rel', 'profiles', '', 'authenticated', 'INSERT'),
  ('rel', 'profiles', '', 'authenticated', 'SELECT'),
  ('rel', 'profiles', '', 'authenticated', 'UPDATE'),
  ('rel', 'profiles', '', 'service_role', 'DELETE'),
  ('rel', 'profiles', '', 'service_role', 'INSERT'),
  ('rel', 'profiles', '', 'service_role', 'SELECT'),
  ('rel', 'profiles', '', 'service_role', 'UPDATE'),
  ('rel', 'reports', '', 'anon', 'DELETE'),
  ('rel', 'reports', '', 'anon', 'INSERT'),
  ('rel', 'reports', '', 'anon', 'SELECT'),
  ('rel', 'reports', '', 'anon', 'UPDATE'),
  ('rel', 'reports', '', 'authenticated', 'DELETE'),
  ('rel', 'reports', '', 'authenticated', 'INSERT'),
  ('rel', 'reports', '', 'authenticated', 'SELECT'),
  ('rel', 'reports', '', 'authenticated', 'UPDATE'),
  ('rel', 'reports', '', 'service_role', 'DELETE'),
  ('rel', 'reports', '', 'service_role', 'INSERT'),
  ('rel', 'reports', '', 'service_role', 'SELECT'),
  ('rel', 'reports', '', 'service_role', 'UPDATE'),
  ('rel', 'votes', '', 'anon', 'DELETE'),
  ('rel', 'votes', '', 'anon', 'INSERT'),
  ('rel', 'votes', '', 'anon', 'SELECT'),
  ('rel', 'votes', '', 'anon', 'UPDATE'),
  ('rel', 'votes', '', 'authenticated', 'DELETE'),
  ('rel', 'votes', '', 'authenticated', 'INSERT'),
  ('rel', 'votes', '', 'authenticated', 'SELECT'),
  ('rel', 'votes', '', 'authenticated', 'UPDATE'),
  ('rel', 'votes', '', 'service_role', 'DELETE'),
  ('rel', 'votes', '', 'service_role', 'INSERT'),
  ('rel', 'votes', '', 'service_role', 'SELECT'),
  ('rel', 'votes', '', 'service_role', 'UPDATE'),
  ('seq', 'images_id_seq', '', 'anon', 'SELECT'),
  ('seq', 'images_id_seq', '', 'anon', 'UPDATE'),
  ('seq', 'images_id_seq', '', 'anon', 'USAGE'),
  ('seq', 'images_id_seq', '', 'authenticated', 'SELECT'),
  ('seq', 'images_id_seq', '', 'authenticated', 'UPDATE'),
  ('seq', 'images_id_seq', '', 'authenticated', 'USAGE'),
  ('seq', 'images_id_seq', '', 'service_role', 'SELECT'),
  ('seq', 'images_id_seq', '', 'service_role', 'UPDATE'),
  ('seq', 'images_id_seq', '', 'service_role', 'USAGE'),
  ('seq', 'leaderboard_entries_id_seq', '', 'anon', 'SELECT'),
  ('seq', 'leaderboard_entries_id_seq', '', 'anon', 'UPDATE'),
  ('seq', 'leaderboard_entries_id_seq', '', 'anon', 'USAGE'),
  ('seq', 'leaderboard_entries_id_seq', '', 'authenticated', 'SELECT'),
  ('seq', 'leaderboard_entries_id_seq', '', 'authenticated', 'UPDATE'),
  ('seq', 'leaderboard_entries_id_seq', '', 'authenticated', 'USAGE'),
  ('seq', 'leaderboard_entries_id_seq', '', 'service_role', 'SELECT'),
  ('seq', 'leaderboard_entries_id_seq', '', 'service_role', 'UPDATE'),
  ('seq', 'leaderboard_entries_id_seq', '', 'service_role', 'USAGE'),
  ('seq', 'leaderboard_weeks_id_seq', '', 'anon', 'SELECT'),
  ('seq', 'leaderboard_weeks_id_seq', '', 'anon', 'UPDATE'),
  ('seq', 'leaderboard_weeks_id_seq', '', 'anon', 'USAGE'),
  ('seq', 'leaderboard_weeks_id_seq', '', 'authenticated', 'SELECT'),
  ('seq', 'leaderboard_weeks_id_seq', '', 'authenticated', 'UPDATE'),
  ('seq', 'leaderboard_weeks_id_seq', '', 'authenticated', 'USAGE'),
  ('seq', 'leaderboard_weeks_id_seq', '', 'service_role', 'SELECT'),
  ('seq', 'leaderboard_weeks_id_seq', '', 'service_role', 'UPDATE'),
  ('seq', 'leaderboard_weeks_id_seq', '', 'service_role', 'USAGE'),
  ('seq', 'reports_id_seq', '', 'anon', 'SELECT'),
  ('seq', 'reports_id_seq', '', 'anon', 'UPDATE'),
  ('seq', 'reports_id_seq', '', 'anon', 'USAGE'),
  ('seq', 'reports_id_seq', '', 'authenticated', 'SELECT'),
  ('seq', 'reports_id_seq', '', 'authenticated', 'UPDATE'),
  ('seq', 'reports_id_seq', '', 'authenticated', 'USAGE'),
  ('seq', 'reports_id_seq', '', 'service_role', 'SELECT'),
  ('seq', 'reports_id_seq', '', 'service_role', 'UPDATE'),
  ('seq', 'reports_id_seq', '', 'service_role', 'USAGE'),
  ('seq', 'votes_id_seq', '', 'anon', 'SELECT'),
  ('seq', 'votes_id_seq', '', 'anon', 'UPDATE'),
  ('seq', 'votes_id_seq', '', 'anon', 'USAGE'),
  ('seq', 'votes_id_seq', '', 'authenticated', 'SELECT'),
  ('seq', 'votes_id_seq', '', 'authenticated', 'UPDATE'),
  ('seq', 'votes_id_seq', '', 'authenticated', 'USAGE'),
  ('seq', 'votes_id_seq', '', 'service_role', 'SELECT'),
  ('seq', 'votes_id_seq', '', 'service_role', 'UPDATE'),
  ('seq', 'votes_id_seq', '', 'service_role', 'USAGE')
),
excluded(t, a, b, role, priv) as (select ''::text, ''::text, ''::text, ''::text, ''::text where false),
out_of_scope(a) as (select ''::text where false)
select 'missing_in_prod' as problem, e.* from expected e
where not exists (select 1 from actual x where x.t = e.t and x.a = e.a and x.b = e.b and x.role = e.role and x.priv = e.priv and x.grantor = 'postgres')
union all
select 'in_prod_not_in_file', x.t, x.a, x.b, x.role, x.priv from actual x
where not exists (select 1 from expected e where e.t = x.t and e.a = x.a and e.b = x.b and e.role = x.role and e.priv = x.priv)
  and not exists (select 1 from excluded e where e.t = x.t and e.a = x.a and e.role = x.role and e.priv = x.priv)
  and x.a not in (select a from out_of_scope)
order by 1, 2, 3, 4, 5, 6;
