-- 20261005000000_explicit_data_api_grants_catchup.sql
--
-- Explicit Data API grants catch-up (Supabase 2026-10-30 default-privileges change).
-- GENERATED by scripts/grants-catchup/build.mjs from manifest.json (prod snapshot
-- 2026-10-05, project yahsswggpgreawugloxi) and scope.json. Do not hand-edit; run render.
--
-- WHY: from 2026-10-30 Supabase stops auto-granting table, sequence, and function
--   privileges in public to anon/authenticated/service_role. Prod keeps what it has,
--   but a REPLAY (local db reset, preview branch, new project) of this repo would
--   create tables nobody can reach, because the earlier migrations never granted.
--   This file re-states the needed subset of prod grants so a replay matches prod.
--
-- WHAT: GRANT-only, existence-guarded, a strict subset of prod. Applying it to prod
--   is a no-op; scripts/grants-catchup/verify-noop.sql proves it (expect zero rows).
--   PUBLIC-executable functions are omitted (the built-in PUBLIC EXECUTE is unaffected).

do $grants$
begin
  if pg_catalog.to_regclass('public.images') is not null then
    grant DELETE, INSERT, SELECT, UPDATE on table public.images to anon;
    grant DELETE, INSERT, SELECT, UPDATE on table public.images to authenticated;
    grant DELETE, INSERT, SELECT, UPDATE on table public.images to service_role;
  end if;
  if pg_catalog.to_regclass('public.leaderboard_entries') is not null then
    grant DELETE, INSERT, SELECT, UPDATE on table public.leaderboard_entries to anon;
    grant DELETE, INSERT, SELECT, UPDATE on table public.leaderboard_entries to authenticated;
    grant DELETE, INSERT, SELECT, UPDATE on table public.leaderboard_entries to service_role;
  end if;
  if pg_catalog.to_regclass('public.leaderboard_weeks') is not null then
    grant DELETE, INSERT, SELECT, UPDATE on table public.leaderboard_weeks to anon;
    grant DELETE, INSERT, SELECT, UPDATE on table public.leaderboard_weeks to authenticated;
    grant DELETE, INSERT, SELECT, UPDATE on table public.leaderboard_weeks to service_role;
  end if;
  if pg_catalog.to_regclass('public.profiles') is not null then
    grant DELETE, INSERT, SELECT, UPDATE on table public.profiles to anon;
    grant DELETE, INSERT, SELECT, UPDATE on table public.profiles to authenticated;
    grant DELETE, INSERT, SELECT, UPDATE on table public.profiles to service_role;
  end if;
  if pg_catalog.to_regclass('public.reports') is not null then
    grant DELETE, INSERT, SELECT, UPDATE on table public.reports to anon;
    grant DELETE, INSERT, SELECT, UPDATE on table public.reports to authenticated;
    grant DELETE, INSERT, SELECT, UPDATE on table public.reports to service_role;
  end if;
  if pg_catalog.to_regclass('public.votes') is not null then
    grant DELETE, INSERT, SELECT, UPDATE on table public.votes to anon;
    grant DELETE, INSERT, SELECT, UPDATE on table public.votes to authenticated;
    grant DELETE, INSERT, SELECT, UPDATE on table public.votes to service_role;
  end if;
  if pg_catalog.to_regclass('public.images_id_seq') is not null then
    grant SELECT, UPDATE, USAGE on sequence public.images_id_seq to anon;
    grant SELECT, UPDATE, USAGE on sequence public.images_id_seq to authenticated;
    grant SELECT, UPDATE, USAGE on sequence public.images_id_seq to service_role;
  end if;
  if pg_catalog.to_regclass('public.leaderboard_entries_id_seq') is not null then
    grant SELECT, UPDATE, USAGE on sequence public.leaderboard_entries_id_seq to anon;
    grant SELECT, UPDATE, USAGE on sequence public.leaderboard_entries_id_seq to authenticated;
    grant SELECT, UPDATE, USAGE on sequence public.leaderboard_entries_id_seq to service_role;
  end if;
  if pg_catalog.to_regclass('public.leaderboard_weeks_id_seq') is not null then
    grant SELECT, UPDATE, USAGE on sequence public.leaderboard_weeks_id_seq to anon;
    grant SELECT, UPDATE, USAGE on sequence public.leaderboard_weeks_id_seq to authenticated;
    grant SELECT, UPDATE, USAGE on sequence public.leaderboard_weeks_id_seq to service_role;
  end if;
  if pg_catalog.to_regclass('public.reports_id_seq') is not null then
    grant SELECT, UPDATE, USAGE on sequence public.reports_id_seq to anon;
    grant SELECT, UPDATE, USAGE on sequence public.reports_id_seq to authenticated;
    grant SELECT, UPDATE, USAGE on sequence public.reports_id_seq to service_role;
  end if;
  if pg_catalog.to_regclass('public.votes_id_seq') is not null then
    grant SELECT, UPDATE, USAGE on sequence public.votes_id_seq to anon;
    grant SELECT, UPDATE, USAGE on sequence public.votes_id_seq to authenticated;
    grant SELECT, UPDATE, USAGE on sequence public.votes_id_seq to service_role;
  end if;
end
$grants$;
